# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - CarwashMrMooon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4  # Clona tu repositorio

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '21'  # Configura Java 21 para el proyecto

      - name: Compile JSP project
        run: |
          javac -cp ./librerias/servlet-api.jar -d ./build/classes $(find ./src -name "*.java")  # Compila los archivos Java
          cp -r ./web/* ./build/web                              # Copia los archivos .jsp y web
          jar -cvf ./target/carwashmrmoon.war -C ./build/web . -C ./build/classes .  # Empaqueta en un WAR

      - name: Upload WAR file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: './mi-aplicacion.war'  # Asegúrate de que el archivo WAR se esté subiendo correctamente

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app  # Descarga el artefacto (el archivo WAR) del job de build

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CarwashMrMooon'  # Nombre de tu App Service en Azure
          slot-name: 'Production'  # Nombre del slot, usualmente 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_39DA7EB819CA47C9819FD73036EDD7AF }}  # Secreto de publicación de Azure
          package: './mi-aplicacion.war'  # Ruta del archivo WAR generado
